#ifndef	__EXTSOUNDFILE_INCLUDED__
#define	__EXTSOUNDFILE_INCLUDED__

enum	EXTSOUNDFILE
{
	ESF_MOEPRO_STRIKE = 0,	// ストライクッ！
	ESF_MOEPRO_BALL,	// ボール
	ESF_MOEPRO_TIME,	// ターイム
	ESF_MOEPRO_OUT,		// アウッ！
	ESF_MOEPRO_SAFE,	// セーフ
	ESF_MOEPRO_FAIRBALL,	// ファール
	ESF_MOEPRO_FOULBALL,	// フェアッ！
	ESF_MOEPRO_BATTEROUT,	// バッターアウッ！
	ESF_MOEPRO_PLAYBALL,	// プレイボール
	ESF_MOEPRO_FOURBALL,	// フォアボー
	ESF_MOEPRO_HOMERUN,	// ホーマンッ！
	ESF_MOEPRO_PITCHER,	// ピチャ交代
	ESF_MOEPRO_OUCH,	// イテッ
	ESF_MOEPRO_AHO,		// あ～ほっ
	ESF_MOEPRO_KNOCK,	// 打撃音
	ESF_MOEPRO_WA,		// ワーッ！（オーライッ？

	ESF_MOETENNIS_00,	// ?
	ESF_MOETENNIS_01,	// ?
	ESF_MOETENNIS_02,	// ラブ
	ESF_MOETENNIS_03,	// フィフティーン
	ESF_MOETENNIS_04,	// サーティ
	ESF_MOETENNIS_05,	// フォーティ
	ESF_MOETENNIS_06,	// アドバンテージ
	ESF_MOETENNIS_07,	// サーバー
	ESF_MOETENNIS_08,	// レシーバー
	ESF_MOETENNIS_09,	// オール
	ESF_MOETENNIS_0A,	// デュース
	ESF_MOETENNIS_0B,	// ?
	ESF_MOETENNIS_0C,	// ショット
	ESF_MOETENNIS_0D,	// 歓声(拍手)
	ESF_MOETENNIS_0E,	// フォールト
	ESF_MOETENNIS_0F,	// レット
	ESF_MOETENNIS_10,	// アウト！
	ESF_MOETENNIS_11,	// ?
	ESF_MOETENNIS_12,	// 体に当たった音?

	ESF_DISKSYSTEM_BOOT,	// カム音
	ESF_DISKSYSTEM_MOTOR,	// モーター音(ループ)
	ESF_DISKSYSTEM_SEEKEND,	// 停止音

	ESF_FILE_MAX
};

#endif	// !__EXTSOUNDFILE_INCLUDED__
